services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - network

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Ab12345.
      POSTGRES_DB: wallet_up
    ports:
      - "5432:5432"
    networks:
      - network

  redis-insight:
    image: redis/redisinsight:latest
    restart: unless-stopped
    ports:
      - "5540:5540"
    depends_on:
      - redis
    networks:
      - network

networks:
  network:
